# Type de recherche
#   - "Publications" : recherche de publications par identifiant Scopus
#   - "Profils"      : recherche de profils d'auteurs par noms, pour une éventuelle
#                      recherche de publications par identifiants Scopus
#search_type = "Profils"
search_type = "Publications"

# Fichier Excel d'entrée et nom du feuillet contenant les information des auteur.e.s
# (colonnes "Nom", "Prénom", ainsi que "Scopus ID" pour les recherches de publications)
#in_excel_file = "pyRefSearchUdeS.xlsx"
in_excel_file = "Liste chercheurs-membres_VF.xlsx"
#in_excel_file = "Liste chercheurs-membres_VF - TEST.xlsx"
in_excel_file_author_sheet = "Membres"

# Gamme d'années pour la recherche de publications (ignoré pour la recherche de profils)
pub_year_first = 2024
pub_year_last = 2024

# Noms d'institutions et d'affiliations considérées commme "locales", pour valider
# les profils d'auteurs dans les recherches
local_affiliations = [
    "Université de Sherbrooke",
    "3IT",
    "Institut interdisciplinaire d'innovation technologique",
    "LN2",
    "Laboratoire nanotechnologies et nanosystèmes",
]

# SCOPUS : Noms et codes à deux lettres pour la recherche par publications
# (Article-ar / Abstract Report-ab / Book-bk / Book Chapter-ch / Conference Paper-cp /
# Conference Review-cr / Data Paper-dp / Editorial-ed / Erratum-er / Letter-le /
# Multimedia-mm / Note-no / Report-rp / Retracted-tb / Review-re / Short Survey-sh)
publication_types = [["Articles", "ar"], ["Confs", "cp"], ["Livres", "bk"],
    ["Chap. de livres", "ch"], ["Lettres", "le"], ["Rapports", "rp"]]

# SCOPUS : Intervalle de mise à jour (en nombre de jours) de la copie locale de la base de données.
# Une recherche en ligne dans Scopus prend beaucoup de temps, les résultats sont
# sauvegardés dans une base de données locale pour éviter de refaire la recherche
# en ligne à chaque fois. Cette base de données locale doit est mise à jour à
# intervalles réguliers (valeur par défaut = 0, i.e. mise à jour à chaque recherche).
scopus_database_refresh = 7

# BREVETS : Activer/désactiver (true/false) la recherche de brevets US et européens (EPO)
uspto_patent_search = true
epo_patent_search = false
